name: flutter_list_movie
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  fluttericon: ^2.0.0
  equatable: ^2.0.3
  rxdart: ^0.27.3
  stream_transform: ^2.0.0
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  page_indicator: ^0.4.1
  transparent_image: ^2.0.0
  carousel_slider: ^4.0.0
  json_annotation: ^4.4.0
  eva_icons_flutter: ^3.0.2
  intl: ^0.17.0

  font_awesome_flutter:
  flutter_rating_bar:
  fluttertoast:
  dropdown_button2:
  animations: ^2.0.0
  add_to_cart_animation:
  animated_background:
  flutter_speed_dial:
  pie_chart:
  grouped_list:
  circular_menu:
  splash_screen_view:
  responsive_grid_list:
  badges:
  sembast: ^3.2.0
  get:
  path:
  google_nav_bar:
  google_fonts:
  syncfusion_flutter_charts:
  side_navigation:
  lottie:
  flutter_typeahead:
  flutter_slider_drawer:
  flutter_easyloading:


  http: ^0.13.3
  flutter_staggered_grid_view: ^0.4.0

  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  path_provider:
  video_player:
  flutter_form_builder:
  draggable_scrollbar:
  cached_network_image:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/img/
    - assets/images/
    - assets/intro/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

    - family: NunitoBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf
